sudo: required
services: docker
env:
  credentials:
  - secure: Vc3ya7CHKJC7t8NqMG39JN3gNK5psAAfe5V55pt6JUacVzydq3xhGywNHeTuohfAsUkMPCSvzrU7bNNqRoq0qVEHxEQzpLe1XVHBDoSf9OTIGr57i+GZOWH8/APKKgtHI7vckYTB1RYBdPMlp+yXtw/9UBrPMcSOQbQwCfxiIkvZfQ/M5D3kGlkqqF2mSgjksysw/8ggPfUHA6nXEt2jaG50fGettQjmwwxqYoGrNoQDlQry9iLF0fMjPezwHCxaPBPKsQzmm+hY/FUxD1R/o7vItoLSZx8ocsCaIFLzrCrTE/1K5DKD8vKAKFyMgdpspIf8+NL+x0Z476o++wo4LkSBl4whcyDxPAJqDijXzw20CdK2zVHBzaR1CQDrFdlNYOl8CDon2298zNjeqvu3XiJC1/a5MOPb59yRJKhrNQ+Z767DgX+dUAyTJSmxpaUapLGxFh5yjqeKI/7UF6wluA3D5kAhCeZBlKeAK5Ess7zZ9lwRjcoBg+dsp6hP94Qape0qGySRcYHYsx7HtQ92nb8uqyk+6fHt8eiJWZ5NuE+Ds4NqWyZLKrDmFGa/J7jDOGZpxo90vq5zG8X3RfPom0XWMvJh8gEY4cWVB8lO7YzG0aWiIFc2/Z6xrP/uis77AyIS5fVTufNyMszSQKg8HaI20EPkB3FsD8v6T6EtJIw=
  - secure: wxOe3fKj6T5jUFC74TuGr8+SJQhtrBXvu8eBOc1clBVrR10YOu6OBbj5fMNHFDAppKesAOlBshRRgtMdmev2WaqVhdoZXYiRM8ZQlO2AhRSgs042xmMElI5+Y0h6zaXC7Tpe8A5o4fBvlo5jhHh5SHPv7DE98wtWwp2P19zc+qEWNgvhHbAKzEhn2x2sbN9C/DS35YEwL8LYMBGyRUUBmdq0kRr0rk4GN6pOc0DuU4yrbsBuXxREWzEjW7lhyeM+2B9jARI0SqXIXX3L2w9IZ74jLLiYCxZD+zsL0ILojDMCQDCJMuN0Wh36Qeb0TGmbZJxK3IPsUGxUz2OeVwWYn34GGz6K+1pJAYNB0zllD/N9O76h2nSvn0MTLeFcKny1c1Ma5kCM529Y70KRZE5Hlz7KVk2GMXl+2B4k6arfYOeg1zDd/70X4i/hM++hglWToF5jrDZ2EsVVrtxvHVhG3Go/emM9IuRugIrqjAsOSiDUVz85iYnK5ffZ3rMox5v3XyJmlXr+8xtQPFTDd0pt9oslYj+datVZfHweAjZBn/jkmtlB2LhHIO19Fg6q+Mbj/2o9eKoNxWurxp5X+E2zLusJ6LbxrQkkju9sdSZ7EKYlu4N0NOm4venaSRIPiC0+P3R4nxvzhm/9dKh4vQIUv7rV+Y0QROvrjcSbDHuKZyU=

script:
  - chmod +x build $DOCKER_USERNAME $DOCKER_PASSWORD
  - "./build"

deploy:
  provider: firebase
  on:
    branch: master
  skip-cleanup: true
  token:
    secure: wwGWXNZwIaUwhZtqqnxp4jAMmXHUWLb7DLBco1jHR1in64SJJgnzTnSV6Zd5qQZsRxVtcOCJb155ataQqf5kEjbWFT1jqwy+8S7D4doZ6Gnd71o1ZNO62YXHZTrc2PHuRrDCt9zuzCfz1GjmMRvwDNeTo0QZi3dszMJFwU3RUqBwMfrhX+/MKU4GuPbLP8puOdWrKTRCUfXQqXIjGLcUttU1e3CLt/feB6Jk+OPS8PBK+NxGVW+lPmr4oEujslQ8vzBvQSNIZdm0kzBsx895NYm/WD9c2itmSs51hOSVeaNpZR9/iRDCSUKBlQus2VAAh2eM6B3wnecOoYjBrxFYfypP3Z4KQ8zvaEyGOmeYxUb/RpImZnfsJZHAHTTmc2x/mbZIEBXrCnJIq4KzviULqDyDo752BbAhERBUtV5T2zQ2E6ywB/GBZ496o3I34MOoVV9sAgj/zigo80Fuqjb0sL0o6nNa6fPV/6FspvguqqXJSPNv0lZ0OzceiByOgMYypJ9rKsRpmrd32RinA5lUqvp3OxB+Jf+p7x6/pCCbp0SZ1jDWI03B7PTLtDt0SArcPhCAK5L2MCGKU9/5ygqJflv9sG8VFI+EWjOv3cm9kdO52sXVCHY9hswEV23y0gTxbRkkg0qPF1NtXHkkH0STGtnHK6SCjByfCmEAT23I4so=
  project: production
