sudo: required
services: docker
env:
  global:
  - secure: sWabovh9anybrpk7lLojwmQE3HA1468uv0AMfkzIZezedDP92wD7G9p8HLm0/iHkJ4SsD7gz5i6b0elEo8SMs2Vk1qhVSyq4na5reHViDClpcuPWeihE0o7TpaJYf8fwUAYT9KzZJhqSLJ5DEiIhnmBE9B0Hp9kGwFqrFRorfljGiDrgr5xDdvtrJTke0nwgneKNsQaOZYsZr1rYj8H3jACcpWctgs4lO93piUUBrGZTFVTOKe3zwmqjw8GftRnBFpcRSCePm80azU49lF+SZ4rAgPObFt0k4IhqCLai32c6XwVVE32CYVbIdGFhcTslLvw+uVu0uuPFgEEuBmqKj5OqC02mJwCfrNtOmLc9XDDuSy81eXSwMUwQMV9wyLohBYysqZgzJImfs4lc4QduPiJY8wjsdfugSWy+I3koaZNgimCQCVI370JCGEC1hAF4wHqU4U0snB6jFyj7C/d60BUFO0VlpNzf6Mkn/t6ttdYlbpU3R7RuMYDJSAC8zYb9vitY0uAUXpYWqtQUhiZX47dlAZSJV2irD/dB+wUkdOHcf5+MQuFckpKgWj8MmhVs56fLWfntCl6kk4zp7piWGfXRc8adYSxTCWI1Xi/vrWYImf31QugnITOAfhMtIG7n9cPZHovDhWrpKK+77CNX8Na3iVX6wT8Z5z9swkM/TO4=
  - secure: k1UFx+Xn3VLfkShFK+uVxI6oV8iKcdqzwNj0c542qxJlM12KY7v+7wziOb6luBWaMUB56iBKOpmdCxl2l1aCKvQBY59FVMx+96inP49hee4sN3BoOnvlqRLktWFfyGujwqPDCyICipr4N1Jjp5aSdfe7eKJONJBTMTcZUC/PNVZ+2soZgtYpVI9QlLB8RX6plSu9+6QFpXijcVo4RwH4NpnVlDar3FLhqyfoZURN5RwSR/u8Eg0gmLnhevNvrIeJACw0ntAZOCM4jVHuOZbNreaGz79mAS6yOsysR3yMFxp/VKdxqze6eV+z5AFPbRu03U8U/eE7T+ZWb9BIJCbSb0/MsTNMCrzXTHLSV5a/j+//qsmTBNamOy0dUgfN2jVWBtyuqJDeWMZXWGsMifkCdfUB34Zutd3lB4snJH1K9CmpP7pXkJ6O2FCDWRjAORWBQyKNoSobX3aPU7s4dfJM+8zALkBSI1tuzCAMpIvwib1BDLWirGaNgMbG6tt5ILokp1FEJY2aDiZNnS0NcmHkxEKbhZydlCAuuqb7OZ/eeCiCXvdGohY86dC0hEkncYHQCjbgyhGn9TtA9Kw4/CGtq6a5UyNsYwA8Hm+do0uufvYggSLxXbb+GYhjohMnay7sP6mgZAeRMj2KgMyZ++Qmxw3cpQFbJQnRbNMJ2GCMawA=

script:
  - chmod +x build $DOCKER_USERNAME $DOCKER_PASSWORD
  - "./build"

deploy:
  provider: firebase
  on:
    branch: master
  skip-cleanup: true
  token:
    secure: wwGWXNZwIaUwhZtqqnxp4jAMmXHUWLb7DLBco1jHR1in64SJJgnzTnSV6Zd5qQZsRxVtcOCJb155ataQqf5kEjbWFT1jqwy+8S7D4doZ6Gnd71o1ZNO62YXHZTrc2PHuRrDCt9zuzCfz1GjmMRvwDNeTo0QZi3dszMJFwU3RUqBwMfrhX+/MKU4GuPbLP8puOdWrKTRCUfXQqXIjGLcUttU1e3CLt/feB6Jk+OPS8PBK+NxGVW+lPmr4oEujslQ8vzBvQSNIZdm0kzBsx895NYm/WD9c2itmSs51hOSVeaNpZR9/iRDCSUKBlQus2VAAh2eM6B3wnecOoYjBrxFYfypP3Z4KQ8zvaEyGOmeYxUb/RpImZnfsJZHAHTTmc2x/mbZIEBXrCnJIq4KzviULqDyDo752BbAhERBUtV5T2zQ2E6ywB/GBZ496o3I34MOoVV9sAgj/zigo80Fuqjb0sL0o6nNa6fPV/6FspvguqqXJSPNv0lZ0OzceiByOgMYypJ9rKsRpmrd32RinA5lUqvp3OxB+Jf+p7x6/pCCbp0SZ1jDWI03B7PTLtDt0SArcPhCAK5L2MCGKU9/5ygqJflv9sG8VFI+EWjOv3cm9kdO52sXVCHY9hswEV23y0gTxbRkkg0qPF1NtXHkkH0STGtnHK6SCjByfCmEAT23I4so=
  project: production
