sudo: required
services: docker
language: node_js
node_js:
  - "stable"
 
env:
  global:
  - secure: Lp0wAw9xYnyXQ3xKJgqDAUMYuv1nkyGUSCxVnZBfdkpVl0ysWHiIJvFTVYK6g0LMyPw7fBw08mbDsLyJ6YWESzpeiUsMwMpGbhmLOERgg2ugy7mj62nwbAPcmfxgpgRYDMwGA0hECH9r8FVqQJURq7C3YLZiH4CisRdyT+yhser2oTrCOvJOmFn+PKWtNeMNCSsoKdYfV5SmOwBzedYOXhYMNQ/3WOFjviuYAR1lb8YE9BL4CjBf0a02ZSl18bOOQX7mdo1b2C4FQ5Ld9QxRzuf3pN+oUy/Ir29Al7uGGlBeWMp8zq4uTL7aDhu7ZRvAtdNSmcMMERf39JH6D3p42+zbuCbDq96943Cr0GEXBFAIziyK3cM0ZjL+efHWjBcVuujohYy6zCtaDaowtb7laE68Y5rrVQE7aSJLdI9IndSVR4P+tOzu+6yvKAooq22f4CiejNK3IR/t7SkS2WE1x0ZTYz804dBYps1LdqfuUs65oGU2QdUxX1q3t8U/RHt04TLQsV5Nik/sFCxCsFGiGZ3C6SYmozwH1GUbke73Tx5rr8Y+rugun0Gtix/+yvXxTkxucCoYp+FALIx4CZWP6NO908PjQmICX2OXzhB40xyc77SXod/KUyQuCn7w/SDDXOTaXgZmmGC3qidxfxO6K5sQyFBs66tpXlK456gsNk0=
  - secure: BnW+yvkKag08o91EJSyHyYKJ9HBYsxXUBDld0JRlgVdWRrRBZRwDr5kkTICQcP5vnqzobKpy2jpO3uaKxKGyNkLltx1t7SAyOzChrYznLIfQIcapsb6wSF6rgMXt5Q+BpfYlpSS5UlsLyIQI+s1FpRD8LDTNmiIv09tiza74YnyViHcmk4/dHBlQ/Xz6eg+o4EJnrckwBrwacTsrzd1Ed2Y8opLosqX2AWNQgIQXDumbECYkMnoPrKgLqTk+YjcQdYojQKFSu2QqPDdlbhRZR6tPxCyCCk35gQobYYFzhROfvpBr37jWg6H8XYDADkIogV4DYw63Fbyzj9KIyu/3OKXQRS4n1Pw5sHUGAN7LjyoQgZXPMlr7knKW2HE1barh23dcX7lywBLNkF/KbO1NknCUPEx6MiDjA9Th+u1OIwbH/HknF8JXqGweVRNoTiCw0Sp/6QePrZycRy77jGW2rsTMTlh9zzHb8BxdWSFVwIaOr3CVdoMMEJsUFHDhFwWmUjyxwGa3lt9AUyRSvdK2LJz6D6rDwDkk2LvJ832zWv+Yvcqvimqizty8/BlwBXpKd3nkjNGmP0snCg5pKilnHGkZQ8xVG8LQfb6SXiM2J5+QEzFLPHxfHZpESBCchfsQ1Ny9p3RTUlRVhpfyodXzvq8zl9Y15zXRX8yGyJc4AC8=
script:
- chmod +x build
- "./build $DOCKER_USERNAME $DOCKER_PASSWORD"

deploy:
  provider: script
  script: bash deploy $FIREBASE_TOKEN production
  on:
    branch: master
  skip-cleanup: true 
