#!/bin/bash
set -ev

echo "building static site"

rm -rf public && \
      mkdir public

docker pull shock01/stefhock-hugo
docker run --rm -v $(pwd)/public:/var/hugo/public -v $(pwd)/content:/var/hugo/content shock01/stefhock-hugo
