#!/bin/bash
set -e
token=$1
project=$2
if [ -z "$token" ]; then
    echo "Usage: <token> <project>" >&2
    exit 1;
fi

if [ -z "$project" ]; then
    echo "Usage: <token> <project>" >&2
    exit 1;
fi

npm install -g firebase-tools --silent
firebase use $project
firebase deploy --token $1
